export const GET_SEARCH_TERM = "GET_SEARCH_TERM";
export const GET_ID = "GET_ID";
export const GET_RECIPE_INFO = "GET_RECIPE_INFO";
export const FETCH_RECIPES = "FETCH_RECIPES";
export const ADD_TO_SHOPPING_LIST = "ADD_TO_SHOPPING_LIST";
